# Generated by Django 2.2.4 on 2019-09-10 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.BUSINESSAREA_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalReferenceGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_metadata.Donor', verbose_name='Donor')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('financial_close_date', models.DateField(blank=True, null=True, verbose_name='Financial Close Date')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('category', models.CharField(choices=[('STD', 'Standard'), ('THE', 'Thematic'), ('FFR', 'FFR')], max_length=16, verbose_name='Category')),
                ('business_areas', models.ManyToManyField(blank=True, to=settings.BUSINESSAREA_MODEL, verbose_name='Business Areas')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_metadata.Donor', verbose_name='Donor')),
                ('external_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.ExternalReferenceGrant', verbose_name='External Reference')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.Theme', verbose_name='Theme')),
            ],
            options={
                'ordering': ['donor'],
            },
        ),
    ]
