# Generated by Django 2.2.5 on 2019-09-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalReferenceGrant',
            new_name='ExternalGrant',
        ),
    ]
