# Generated by Django 2.2.5 on 2019-09-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0002_auto_20190920_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='external_reference',
            new_name='external_grant',
        ),
    ]
