# Generated by Django 3.1 on 2020-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_metadata", "0008_secondarydonor"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
