# Generated by Django 3.2.13 on 2022-05-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_realm', '0001_initial'),
        ('report_metadata', '0010_drpmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='businessareas',
            field=models.ManyToManyField(blank=True, to='unicef_realm.BusinessArea', verbose_name='Business Areas'),
        ),
    ]
