# Generated by Django 4.0.5 on 2022-06-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0010_drpmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='business_areas',
        ),
    ]
