# Generated by Django 4.0.5 on 2022-06-08 15:03

from django.db import migrations


def clean_metadata(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    qs = ContentType.objects.filter(app_label="unicef_security", model__in=["region", "businessarea"])
    qs.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("report_metadata", "0012_grant_business_areas"),
    ]

    operations = [migrations.RunPython(clean_metadata, migrations.RunPython.noop)]
