# Generated by Django 5.1.4 on 2024-12-29 17:57

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_metadata", "0013_auto_20220608_1003"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=36, verbose_name="Name")),
                (
                    "source_id",
                    models.CharField(max_length=36, verbose_name="Source ID"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="Default filters"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
