dist: jammy
language: python

python:
  - "3.11"

env:
  global:
    - DATABASE_URL=psql://postgres:pass@127.0.0.1:5432/donor_reporting_portal
    - HOST=http://localhost:8082
    - SECRET_KEY=top-secret
    - INSIGHT_URL=https://uniapis.unicef.org/biapi/v1/
    - SHAREPOINT_CONNECTION=user
  jobs:
    - DJANGO=4.1

services:
  - postgres

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
    - redis-tools
    - redis-server

install:
  - pip install tox codecov

script:
  - tox -e "d${DJANGO//.}" -- py.test tests -v

before_script:
  - psql -c "CREATE DATABASE donor_reporting_portal;" -U postgres

after_success:
  - coverage combine
  - codecov