dist: xenial
language: python

python:
  - 3.8

env:
  global:
    - DATABASE_URL=psql://postgres:pass@127.0.0.1:5432/donor_reporting_portal
    - HOST=http://localhost:8082
    - SECRET_KEY=top-secret
    - INSIGHT_URL=https://uniapis.unicef.org/biapi/v1/
    - VISION_URL=https://uniapis.unicef.org/biapi/v1/
  jobs:
    - DJANGO=3.0

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - redis

install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}" -- py.test tests -v

before_script:
  - psql -c "CREATE DATABASE donor_reporting_portal;" -U postgres

after_success:
  - coverage combine
  - codecov