dist: bionic
language: python
sudo: false

python:
  - 3.8

env:
  - DJANGO=2.2

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

services:
  - redis-server

install:
  - pip install tox codecov

script:
  - sudo apt-get install -y postgresql-plpython3-12 python3 python3-redis
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}" -- py.test tests -v

before_script:
  - psql -c "CREATE DATABASE donor_reporting_portal;" -U postgres

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
