dist: xenial
language: python

python:
  - 3.8

env:
  - DJANGO=3.0

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - redis

install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}" -- py.test tests -v

before_script:
  - psql -c "CREATE DATABASE donor_reporting_portal;" -U postgres

after_success:
  - coverage combine
  - codecov