# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- develop

resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: pg10
    image: postgres:10
    
pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      PYTHON_VERSION: '3.8'
  maxParallel: 3

container: my_container

services:
  postgres: pg10

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools wheel pipenv
    python -m pipenv lock -r > requirements.txt
    python -m pipenv lock --dev -r > dev_requirements.txt
    pip install -r requirements.txt
    pip install -r dev_requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    tox
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()
