properties = {
    "RefinableDate09": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_CREATED",
        "Alias": "DRPCREATED",
    },
    "RefinableDate11": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_MODIFIED",
        "Alias": "DRPMODIFIED",
    },
    "RefinableDate14": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_GRANTEXPIRYDATE",
        "Alias": "DRPGRANTEXPIRYDATE",
    },
    "RefinableDate15": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_REPORTENDDATE",
        "Alias": "DRPREPORTENDDATE",
    },
    "RefinableString160": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_DONOR",
        "Alias": "DRPDONOR",
    },
    "RefinableString161": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_GRANTNUMBER",
        "Alias": "DRPGRANTNUMBER",
    },
    "RefinableString162": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FRAMEWORKAGREEMENT",
        "Alias": "DRPFRAMEWORKAGREEMENT",
    },
    "RefinableString163": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_DONORDOCUMENT",
        "Alias": "DRPDONORDOCUMENT",
    },
    "RefinableString164": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_REPORTGROUP",
        "Alias": "DRPREPORTGROUP",
    },
    "RefinableString165": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_RECIPIENTOFFICE",
        "Alias": "DRPRECIPIENTOFFICE",
    },
    "RefinableString166": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_REPORTSTATUS",
        "Alias": "DRPREPORTSTATUS",
    },
    "RefinableString167": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_GRANTISSUEYEAR",
        "Alias": "DRPGRANTISSUEYEAR",
    },
    "RefinableString168": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_EXTERNALREFERENCE",
        "Alias": "DRPEXTERNALREFERENCE",
    },
    "RefinableString169": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_REPORTTYPE",
        "Alias": "DRPREPORTTYPE",
    },
    "RefinableString170": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_THEME",
        "Alias": "DRPTHEME",
    },
    "RefinableString171": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_DONORREPORTCATEGORY",
        "Alias": "DRPDONORREPORTCATEGORY",
    },
    "RefinableString172": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_REPORTMETHOD",
        "Alias": "DRPREPORTMETHOD",
    },
    "RefinableString173": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_RETRACTED",
        "Alias": "DRPRETRACTED",
    },
    "RefinableString174": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_REPORTGENERATEDBY",
        "Alias": "DRPREPORTGENERATEDBY",
    },
    "RefinableString175": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_DONORCODE",
        "Alias": "DRPDONORCODE",
    },
    "RefinableString176": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_AWARDTYPE",
        "Alias": "DRPAWARDTYPE",
    },
    "RefinableDate06": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_SOAISSUEDATE",
        "Alias": "CTNSOAISSUEDATE",
    },
    "RefinableDate07": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_FUNDSDUEDATE",
        "Alias": "CTNFUNDSDUEDATE",
    },
    "RefinableDate08": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_SENTTOGAVIDATE",
        "Alias": "CTNSENTTOGAVIDATE",
    },
    "RefinableString136": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_UNICEFWBS",
        "Alias": "CTNUNICEFWBS",
    },
    "RefinableString137": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_URGENT",
        "Alias": "CTNURGENT",
    },
    "RefinableString138": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_REPORTMODIFIEDBY",
        "Alias": "CTNREPORTMODIFIEDBY",
    },
    "RefinableString139": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_VENDOR",
        "Alias": "CTNVENDOR",
    },
    "RefinableString140": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_CTNNUMBER",
        "Alias": "CTNNUMBER",
    },
    "RefinableString141": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_MOLNUMBER",
        "Alias": "CTNMOLNUMBER",
    },
    "RefinableString142": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_MOUREFERENCE",
        "Alias": "CTNMOUREFERENCE",
    },
    "RefinableString143": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_GAVIWBS",
        "Alias": "CTNGAVIWBS",
    },
    "RefinableString144": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_COUNTRYNAME",
        "Alias": "CTNCOUNTRYNAME",
    },
    "RefinableString145": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_VACCINETYPE",
        "Alias": "CTNVACCINETYPE",
    },
    "RefinableString146": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_PURCHASEORDER",
        "Alias": "CTNPURCHASEORDER",
    },
    "RefinableString147": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_MATERIALCODE",
        "Alias": "CTNMATERIALCODE",
    },
    "RefinableString148": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_APPROVALYEAR",
        "Alias": "CTNAPPROVALYEAR",
    },
    "RefinableString149": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_PREPAIDSTATUS",
        "Alias": "CTNPREPAIDSTATUS",
    },
    "RefinableString150": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_CASENUMBER, OWS_Q_TEXT_ALLOCATIONROUND",
        "Alias": "CTNALLOCATIONROUND",
    },
}
