properties = {
    "RefinableDate06": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_SOAISSUEDATE",
        "Alias": "CTNSOAISSUEDATE",
    },
    "RefinableDate07": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_FUNDSDUEDATE",
        "Alias": "CTNFUNDSDUEDATE",
    },
    "RefinableDate08": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_SENTTOGAVIDATE",
        "Alias": "CTNSENTTOGAVIDATE",
    },
    "RefinableString136": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_UNICEFWBS",
        "Alias": "CTNUNICEFWBS",
    },
    "RefinableString137": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_URGENT",
        "Alias": "CTNURGENT",
    },
    "RefinableString138": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_REPORTMODIFIEDBY",
        "Alias": "CTNREPORTMODIFIEDBY",
    },
    "RefinableString139": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_VENDOR",
        "Alias": "CTNVENDOR",
    },
    "RefinableString140": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_CTNNUMBER",
        "Alias": "CTNNUMBER",
    },
    "RefinableString141": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_MOLNUMBER",
        "Alias": "CTNMOLNUMBER",
    },
    "RefinableString142": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_MOUREFERENCE",
        "Alias": "CTNMOUREFERENCE",
    },
    "RefinableString143": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_GAVIWBS",
        "Alias": "CTNGAVIWBS",
    },
    "RefinableString144": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_COUNTRYNAME",
        "Alias": "CTNCOUNTRYNAME",
    },
    "RefinableString145": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_VACCINETYPE",
        "Alias": "CTNVACCINETYPE",
    },
    "RefinableString146": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_PURCHASEORDER",
        "Alias": "CTNPURCHASEORDER",
    },
    "RefinableString147": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_R_MTXT_MATERIALCODE",
        "Alias": "CTNMATERIALCODE",
    },
    "RefinableString148": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_APPROVALYEAR",
        "Alias": "CTNAPPROVALYEAR",
    },
    "RefinableString149": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_PREPAIDSTATUS",
        "Alias": "CTNPREPAIDSTATUS",
    },
    "RefinableString150": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_CASENUMBER, OWS_Q_TEXT_ALLOCATIONROUND",
        "Alias": "CTNALLOCATIONROUND",
    },
}
