# Generated by Django 3.0.3 on 2020-03-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0008_secondarydonor'),
        ('roles', '0004_auto_20200220_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='secondary_donor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='report_metadata.SecondaryDonor'),
        ),
    ]
