# Generated by Django 3.2.4 on 2022-01-28 16:54

from django.db import migrations


def migrate_workspace(apps, schema_editor):
    UserRole = apps.get_model("roles", "UserRole")
    UserRole.objects.update(notification_period="none")


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0007_alter_userrole_notification_period"),
    ]

    operations = [migrations.RunPython(migrate_workspace, migrations.RunPython.noop)]
