# Generated by Django 4.2.1 on 2023-09-05 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0010_alter_userrole_secondary_donor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "permissions": (("can_view_all_donors", "Can views all Donors"), ("is_unicef_user", "Is UNICEF User")),
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
            },
        ),
    ]
