# Generated by Django 2.2.7 on 2019-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharepoint", "0003_auto_20191105_1127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharepointsite",
            name="wrapper_name",
        ),
        migrations.AddField(
            model_name="sharepointsite",
            name="site_type",
            field=models.CharField(
                default="sites", max_length=16, verbose_name="Site Type"
            ),
        ),
    ]
