# Generated by Django 2.2.10 on 2020-02-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint', '0007_auto_20200129_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepointsite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sharepoint.SharePointTenant'),
        ),
    ]
