# Generated by Django 2.2.8 on 2020-02-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint', '0008_auto_20200206_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharepointsite',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='SharePointLibrary',
        ),
        migrations.DeleteModel(
            name='SharePointSite',
        ),
        migrations.DeleteModel(
            name='SharePointTenant',
        ),
    ]
