# Generated by Django 2.2.10 on 2020-02-20 16:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sharepoint", "0009_auto_20200220_0939"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharePointGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
            ],
            options={
                "verbose_name": "SharePoint Group",
                "verbose_name_plural": "SharePoint Groups",
                "ordering": ["name"],
            },
        ),
    ]
