# Generated by Django 3.0.9 on 2020-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint_rest_api', '0001_initial'),
        ('sharepoint', '0010_sharepointgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepointgroup',
            name='libs',
            field=models.ManyToManyField(related_name='groups', to='sharepoint_rest_api.SharePointLibrary'),
        ),
    ]
